CREATE DATABASE todolist;

create table tl_user
(
NOME VARCHAR(255) NOT NULL
,EMAIL VARCHAR(255) NOT NULL
,PWORD VARCHAR(128) NOT NULL
,ATIVO BIT NOT NULL DEFAULT 1
,PRIMARY KEY (EMAIL)
);

CREATE TABLE `td_list_data` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`EMAIL` VARCHAR(255) NOT NULL COMMENT 'DONO DA TODO LIST',
	`TODO` TEXT NULL,
	`DATACREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
);
